serviceproj/views/admin_backup.py
# serviceproj\views\backup.py
import os
import glob
from flask import Blueprint, render_template, abort, request, redirect, url_for, flash
from flask_login import login_required, current_user
from sqlalchemy.sql import func, text
from datetime import datetime

from serviceproj import db
from serviceproj.views.main import menu
from serviceproj.models import Device, ServiceDevice, Service, WorkshopService, ServiceList, Role, Order

backup_bp = Blueprint('backup', __name__)

@backup_bp.route("/admin_backup", methods=['GET', 'POST'])
@login_required
def admin_backup():
    role = Role.query.filter_by(id=current_user.role_id).first()
    if role.role_name != "admin":
        abort(403)
    dump_dir = '/tmp/'
    dump_files = glob.glob(os.path.join(dump_dir, "*.dump"))
    return render_template("admin_backup.html", pathes=dump_files)

@backup_bp.route("/create_backup", methods=['POST'])
@login_required
def create_backup():
    now = datetime.now()
    filepath = '/tmp/dump-' + now.strftime("%Y-%m-%d-%H") + '.dump'
    db.session.execute(text(f"SELECT public.create_dump('{filepath}')"))
    flash("Бэкап успешно создан", "success")
    return redirect(url_for("backup.admin_backup"))

@backup_bp.route("/delete_backup/<path:path>", methods=['POST'])
@login_required
def delete_backup(path):
    db.session.execute(text(f"SELECT public.delete_dump('{"/"+path}')"))
    flash(f"Бэкап '{path}' успешно удалён!", "success")
    return redirect(url_for("backup.admin_backup"))

serviceproj/views/auth.py
#serviceproj/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import text

from serviceproj import app, db, login_manager
from serviceproj.models import Client, Employee, Role

auth_bp = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(phone_number):
    if not phone_number:
        logout_user()
        return render_template('login.html')
    phone_number = session["phone_number"]
    user = Employee.query.filter_by(phone_number=phone_number).first()
    if user is None:
        user = Client.query.filter_by(phone_number=phone_number).first()
    return user

login_manager.init_app(app)

def register_client(phone, password, first_name, last_name, patronymic):
    query = text("""
        SELECT register_client(
            :phone,
            :password,
            :first_name,
            :last_name,
            :patronymic
        )
    """)
    # Выполняем запрос и возвращаем результат
    result = db.session.execute(query, {
        "phone": phone,
        "password": password,
        "first_name": first_name,
        "last_name": last_name,
        "patronymic": patronymic
    }).scalar()
    return result


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        patronymic = request.form.get('patronymic')
        phone = request.form.get('phone')
        psw = request.form.get('psw')
        psw_again = request.form.get('psw_again')

        # Проверяем, что все поля заполнены
        if not (phone and psw and psw_again and patronymic and first_name and last_name):
            flash('Заполните все поля')
        # Проверяем, что пароли совпадают
        elif psw != psw_again:
            flash('Введите одинаковые пароли')
        # Проверяем длину номера телефона
        elif not phone.isdigit() or len(phone) != 11:
            flash('Номер телефона должен содержать ровно 11 цифр (без символов и пробелов)')
        else:
            # Убираем '+' (если добавили это условие)
            phone = phone.lstrip('+')

            # Хэшируем пароль
            hashed_password = generate_password_hash(psw)

            try:
                # Вызываем функцию регистрации
                result = register_client(
                    phone=phone,
                    password=hashed_password,
                    first_name=first_name,
                    last_name=last_name,
                    patronymic=patronymic
                )

                if result:
                    flash('Регистрация прошла успешно!')
                    return redirect(url_for('auth.login'))
                else:
                    flash('Клиент с таким номером телефона уже существует')
            except Exception as e:
                print(f"Ошибка: {e}")
                flash('Произошла ошибка при регистрации. Пожалуйста, попробуйте снова.')

    return render_template('register.html')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    if request.method == 'POST':
        phone_number = request.form.get('phone_number')[1:]
        password = request.form.get('password')

        if phone_number and password: 
            user = Client.query.filter_by(phone_number=phone_number).first()
            if not user:
                user = Employee.query.filter_by(phone_number=phone_number).first()
                
            if user and check_password_hash(user.password, password):
                login_user(user)
                session['phone_number'] = phone_number  # Сохраняем номер телефона
                return redirect(url_for('profile.profile'))
            else:
                flash('Логин или пароль некорректны')
        else:
            flash('Заполните все поля')

    return render_template('login.html')

@auth_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@auth_bp.app_errorhandler(401)
def handle_401(e):
    return render_template('unauthorized.html'), 401

serviceproj/views/order.py
#serviceproj\views\order.py
from flask import Blueprint, render_template, abort, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.sql import func, text
import datetime

from serviceproj import db
from serviceproj.views.main import menu
from serviceproj.models import Device, ServiceDevice, Service, WorkshopService, ServiceList, Role, Order
order_bp = Blueprint('order', __name__)

def get_data():
    # Query the Device and WorkshopService models
    services = Service.query.all()
    print(services)

    #TODO девайсы только нужного сервиса по DeviceServices, услуги только по service_list
    devices = Device.query.all()
    workshop_services = WorkshopService.query.all()
    
    # Return the data as dictionaries or objects as needed
    return {
        "devices": devices,
        "workshop_services": workshop_services,
        "services" : services
    }

def get_filtered_data(service_id):
    devices = db.session.query(Device).join(ServiceDevice).filter(ServiceDevice.service_id == service_id).all()
    workshop_service_data = db.session.execute(text("SELECT * FROM get_workshop_services(:service_id)"), {'service_id': service_id}).fetchall()
    # Преобразуем данные в объекты WorkshopService потому что переделывать свойства на индексы
    workshop_services = [
        WorkshopService(id=ws[0], description=ws[1], cost=ws[2])
        for ws in workshop_service_data
    ]
    return {
        "devices": devices,
        "workshop_services": workshop_services
    }

@order_bp.route("/make_order", methods=['GET', 'POST'])
@login_required
def make_order():
    role = Role.query.filter_by(id=current_user.role_id).first()
    if role.role_name != "client":
        abort(403)

    if request.method == 'POST':
        service_idx = int(request.form.get("serviceAddress").split(" ")[-1])
        device_model = request.form.get("deviceModel")
        description = request.form.get("description")        
        service = Service.query.filter(Service.box_index==service_idx).first()
        device = Device.query.filter(Device.title==device_model).first()
        order = Order(
            service_id=service.id,
            client_id=current_user.id,
            device_id=device.id,
            total_price=0,
            date=func.now(),
            problem=description
        )
        db.session.add(order)
        db.session.commit()
    data = get_data()
    return render_template("order.html",
                            menu=menu,
                            services=data["services"],
                            devices=[],
                            workshop_services=[])

@order_bp.route("/filter_data", methods=['POST'])
def filter_data():
    service_address = request.form.get('serviceAddress')
    # Найти выбранный сервис по адресу
    selected_service = Service.query.filter_by(box_index=service_address.split(' ')[-1]).first()
    if not selected_service:
        return {'error': 'Service not found'}, 404
    # Получить устройства и услуги, связанные с выбранным сервисом
    filtered_data = get_filtered_data(selected_service.id)
    
    return {
        'devices': [{'title': d.title} for d in filtered_data['devices']],
        'workshop_services': [{'description': ws.description} for ws in filtered_data['workshop_services']]
    }

serviceproj/views/repair.py
from flask import Blueprint, render_template, abort, request, redirect, url_for, jsonify
from flask_login import login_required, current_user
from sqlalchemy import text
from serviceproj import db
from serviceproj.views.main import menu
from serviceproj.models import Order, Service, Role, WorkshopService, ServiceList, OrderServices

repair_bp = Blueprint('repair', __name__)

@repair_bp.route("/close_order/<task_id>", methods=['GET', 'POST'])
@login_required
def close_order(task_id=None):
    user = current_user
    role = Role.query.filter_by(id=user.role_id).first()    
    if role.role_name != 'employee':
        abort(403)
    if task_id is None:
        return render_template("unknown_order")    
    order = Order.query.filter_by(id=task_id).first()
    if request.method == 'POST':
        # Получаем данные из запроса
        data = request.form.getlist('serviceType')  # Получаем список услуг
        print(data)    
    return render_template("repair.html", menu=menu, order=order)

@repair_bp.route("/filter_workshop_services/", methods=['POST'])
@login_required
def filter_workshop_services():
    user = current_user
    role = Role.query.filter_by(id=user.role_id).first()
    if role.role_name != 'employee':
        abort(403)
    workshop_service_data = db.session.execute(text("SELECT * FROM get_workshop_services(:service_id)"), {'service_id': current_user.service_id}).fetchall()
    workshop_services = [
        {"description": ws[1], "cost": ws[2]} 
        for ws in workshop_service_data
    ]
    return jsonify(workshop_services)


@repair_bp.route("/calc_order/", methods=['GET', 'POST'])
@login_required
def calc_order():
    user = current_user
    role = Role.query.filter_by(id=user.role_id).first()
    if role.role_name != 'employee':
        abort(403)
    
    if request.method == 'POST':
        data = request.get_json()  # Получаем данные из POST-запроса
        services = data.get('services', [])
        order_id = data.get('order_id', None)  # Получаем order_id, если он есть

        print(f"Полученные данные: {data}")
        print(f"order_id: {order_id}, services: {services}")

        if not order_id:
            print("Ошибка: не передан order_id")
            abort(400)  # Если order_id пустой, возвращаем ошибку

        try:
            # Начинаем транзакцию вручную
            db.session.execute(text("BEGIN TRANSACTION"))

            # Удаляем не актуальные услуги для заказа
            OrderServices.query.filter_by(order_id=order_id).delete()

            # Добавляем новые услуги
            for work in services:
                work = " ".join(work.split(" ")[:-1])  # Убираем стоимость
                work_id = WorkshopService.query.filter(WorkshopService.description == work).first().id
                new_order_service = OrderServices(
                    order_id=order_id,
                    work_id=work_id
                )          
                db.session.add(new_order_service)

            # Обновляем статус заказа
            db.session.query(Order).filter(Order.id == order_id).update(
                {'status': 'Выполнено'}
            )

            # Коммитим транзакцию
            db.session.commit()

        except Exception as e:
            # Если возникла ошибка, откатываем транзакцию
            db.session.rollback()
            print(f"Ошибка транзакции: {e}")
            abort(500)

        finally:
            # очищаем сессию
            db.session.remove()

        return redirect(url_for('profile.profile'))

serviceproj/templates/admin_backup.html
{% extends 'base.html' %}

{% block content %}
  <h1>Управление сейвпоинтами</h1>

  <h1>Сейвпоинты</h1>
  <head>
    <meta charset="UTF-8">
    <title>Savepoints</title>
</head>

<body>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <div class="flashes">
      {% for category, message in messages %}
      <div class="flash {{ category }}">{{ message }}</div>
      {% endfor %}
  </div>
  {% endif %}
  {% endwith %}
  <div class="profile-container">
      <h1>Бекапы</h1>

      <form action="{{ url_for('backup.create_backup') }}" method="post" style="margin-bottom: 20px;">
          <button type="submit">Создать бекап</button>
      </form>

      <table>
          <tbody>
              {% for path in pathes %}
              <tr>
                  <td>{{ path }}</td>
                  <td>
                      <div class="actions">
                          <form action="{{ url_for('backup.delete_backup', path=path) }}" method="post" style="margin: 0;">
                              <input type="hidden" name="path" value="{{ path }}">
                              <button type="submit">Удалить</button>
                          </form>
                      </div>
                  </td>
              </tr>
              {% else %}
              <tr>
                  <td colspan="2" style="text-align: center;">Нет задач</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>

  </div>
</body>

  
{% endblock %}

serviceproj/templates/admin_profile.html

{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {{ super() }}

<body>
    <footer>
        <div class="container">      
            панель администратора
            <a href="{{ url_for('auth.logout') }}">Выйти</a>
        </div>
    </footer>
    {% for cat, msg in get_flashed_messages(True) %}
    <div class="flash {{cat}}">{{msg}}</div> 
    {% endfor %}
    
    <div class="profile-container">
            <form action="{{ url_for('profile.admin_profile') }}" method="POST">
                <h3>Добавить работника</h3>

                <div>
                    <input type="text" name="stype" list="manage_type" placeholder="Добавить/Изменить или удалить работника">
                    <datalist id="manage_type">
                        {% for type in manage_type %}
                        <option value="{{ type }}">
                        {% endfor %}
                    </datalist>
                </div>

                <input type="text" name="employee_number" placeholder="Номер телефона">
                <input type="text" name="employee_first_name" placeholder="Имя">
                <input type="text" name="employee_last_name" placeholder="Фамилия">
                <input type="text" name="employee_patronymic" placeholder="Отчество">
                <input type="text" name="employee_salary" placeholder="Зарплата">
                <input type="text" name="employee_service_id" placeholder="ID Сервиса">
                <input type="text" name="employee_password" placeholder="пароль ">
                
                <input type="hidden" name="form_type" value="employee_form">
                <button type="submit">Отправить</button>
            </form>
            
        </form>
    </div>

    <div class="profile-container">
        <form action="{{ url_for('profile.admin_profile') }}" method="POST">
            <h3>Добавить сервис</h3>

            <div>
                <input type="text" name="stype" placeholder="Добавить/Изменить или удалить сервис">
                <datalist>
                    <option value="Добавить/обновить">
                </datalist>
            </div>
            <input type="text" name="service_index" placeholder="Индекс">
            <input type="text" name="service_spec" placeholder="Специализация">
            <input type="text" name="service_address" placeholder="Адрес">
            <input type="text" name="service_number" placeholder="Номер дома">
            <input type="hidden" name="form_type" value="service_form">
            <button type="submit">Отправить</button>
        </form>
    </div>

    <div class="profile-container">
        <form action="{{ url_for('profile.admin_profile') }}" method="POST">
            <h3>Добавить услугу</h3>

            <div>
                <input type="text" name="stype" list="manage_type" placeholder="Добавить/Изменить или удалить услугу">
                <datalist id="manage_type">
                    {% for type in manage_type %}
                    <option value="{{ type }}">
                    {% endfor %}
                </datalist>
            </div>

            <input type="text" name="service_index_for_details" placeholder="выбрать сервис">
            <input type="text" name="service_description" placeholder="описание услуги">
            <input type="text" name="service_price" placeholder="Цена">
            <input type="text" name="ws_id" placeholder="id услуги (для удаления)">

            <input type="hidden" name="form_type" value="service_details_form">
            <button type="submit">Отправить</button>
        </form>
    </div>

    
    <div class="profile-container">
        <form action="{{ url_for('profile.admin_profile') }}" method="POST">
            <h3>Добавить девайс</h3>

            <input type="text" name="service_index_for_device" placeholder="выбрать сервис">
            <input type="text" name="device_title" placeholder="название">
            <input type="text" name="device_type" placeholder="тип">
            <input type="hidden" name="form_type" value="device_form">
            <button type="submit">Отправить</button>
        </form>
    </div>

<div class="profile-container" >
    <form action="{{ url_for('backup.admin_backup') }}" >
        <button type="submit">Управление откатами </button>
    </form>
    
</div>

</body>

{% endblock %}

serviceproj/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block title %}
        {% if title %}
            <title>{{title}}</title>
        {% endif %}
    {% endblock %}
    {% block styles %}

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

</head>
<body>
    {% block content %}
        {% block mainmenu %}
            <header>
                <div class="container">
                    <h1><a href="{{url_for(menu[0].url)}}"> {{menu[0].name}}</a></h1>
                    <nav>
                        <ul>
                            {% for m in menu[1:] %}
                            <li>
                                <a href="{{url_for(m.url)}}"> {{m.name}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </header>
        {% endblock mainmenu %}
        
    {% endblock content %}
    <footer>
        <div class="container">
            <p>&copy; 2025 Repair service</p>
        </div>
    </footer>
</body>

</html>

serviceproj/templates/employee_profile.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {{ super() }}
    <body>
        <a href="{{ url_for('auth.logout') }}">Выйти</a>
        <div >
            <h1>Страница работника</h1>
            <div>
            </div>
    
            <table >
                <thead>
                    <tr>
                        <td>id</td>
                        <th>Проблема</th>
                        <th>Дата</th>
                        <th>Девайс</th>
                        <th>Статус</th>
                        <th>Выполнить</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>{{ task.name }}</td>
                        <td>{{ task.date }}</td>
                        <td>{{ task.device }}</td>
                        <td>{{ task.status }}</td>
                        <td>
                            <form action="{{ url_for('repair.close_order', task_id=task.id) }}" method="post">
                                <input type="hidden" name="task_id" value="{{ task.id }}">
                                <button type="submit" >Выполнить</button>
                            </form>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="3" style="text-align: center;">Нет задач</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>

    
{% endblock %}

serviceproj/templates/error.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ошибка</title>
</head>
<body>
    <h1>Произошла ошибка</h1>
    <p>{{ message }}</p>
    <a href="{{ url_for('repair.close_order', task_id=task_id) }}">Попробовать снова</a>
</body>
</html>

serviceproj/templates/index.html

{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {{ super() }}

    <section class="features">
        <div class="container">
            <div class="feature">
                <h3>Более 100 мастеров в штате</h3>
                <img src="{{url_for('static', filename='serv3.jpg')}}" />
                <p>лучшее качество за минимальное время</p>
            </div>
            <div class="feature">
                <h3>Мы знаем что делаем</h3>
                <img src="{{url_for('static', filename='serv1.jpg')}}" />
                <p>Каждый работник имеет сертификат о квалификации</p>
            </div>
            <div class="feature">
                <h3>Квалифицированный персонал</h3>
                <img src="{{url_for('static', filename='serv2.jpg')}}" />
                <p>Лучший ремонт на рынке</p>
            </div>
        </div>

        <h1><a href="{{ url_for('order.make_order') }}" class="btn"> Сделать заказ</a></h1>
    </section>

    <div class="img-block">
        
    </div>

    <div class="img-block">
        
    </div>

    <div class="img-block">
        
    </div>
{% endblock %}

serviceproj/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <div class="modern-content-page">
        <div class="register-container">
            <h1>Авторизация</h1>
            {% for cat, msg in get_flashed_messages(True) %}
            <div class="flash {{cat}}">{{msg}}</div> 
            {% endfor %}
            <form method="post" class="register-form">

                <div class="form-group">
                    <label for="phone">Номер телефона:</label>
                    <input type="tel" id="phone" name="phone_number" required>
                </div>

                <div class="form-group">
                    <label for="psw">Пароль:</label>
                    <input type="tel" id="psw" name="password" required>
                </div>

                <input type="submit" class="btn-primary" value="Войти">
            </form>

            <div class="form-footer">
                <p>Еще нет аккаунта? <a href="{{ url_for('auth.register') }}" class="login-link">Регистрация</a></p>
            </div>

        </div>
    </div>
</body>
</html>

serviceproj/templates/order.html
{% extends 'base.html' %}

{% block title %}
    <title>Личный кабинет</title>
{% endblock %}

{% block content %}
    {{ super() }}
    <body>
        <header>
            {% for cat, msg in get_flashed_messages(True) %}
            <div class="flash {{cat}}">{{msg}}</div> 
            {% endfor %}
            <h1>Оформление заказа</h1>
        </header>
        <main>
            <div class="profile-container">
                <form id="order-form" action="{{ url_for('order.make_order') }}" method="post">
                    <div class="form-group">
                        <label for="device-model">Выберите удобный сервис</label>
                        <input type="text" id="service-address" name="serviceAddress" list="services" placeholder="Введите адрес" value="{{ selected_service.street if selected_service else '' }}">
                        <datalist id="services">
                            {% for service in services %}
                            <option value="{{ service.street }} д.{{ service.home_number  }} {{ service.specialization }}  {{ service.box_index }}">
                            {% endfor %}
                        </datalist>
                    </div>
            
                    <div class="form-group">
                        <label for="device-model">Модель устройства:</label>
                        <input type="text" id="device-model" name="deviceModel" list="devices" placeholder="Введите модель устройства">
                        <datalist id="devices">
                            {% for model in devices %}
                            <option value="{{ model.title }}">
                            {% endfor %}
                        </datalist>
                    </div>
            
                    <div class="form-group">
                        <label for="service-type">Тип услуги:</label>
                        <input type="text" id="service-type" name="serviceType" list="workshop_services" placeholder="Выберите тип услуги">
                        <datalist id="workshop_services">
                            {% for w_service in workshop_services %}
                            <option value="{{ w_service.description }}">
                            {% endfor %}
                        </datalist>
                    </div>
            
                    <div class="form-group">
                        <label for="description">Описание проблемы:</label>
                        <textarea id="description" name="description" rows="5" placeholder="Опишите проблему"></textarea>
                    </div>
            
                    <button>Отправить заказ</button>
                </form>
            
                {% if error %}
                <p style="color:red;">{{ error }}</p>
                {% endif %}
                <script src="{{ url_for('static', filename='js/filter_orderdata.js') }}"></script>
            </div>
        </main>
    </body>
{% endblock %}

serviceproj/templates/profile.html

{% extends 'base.html' %}

{% block title %}
    <title>Личный кабинет</title>
{% endblock %}

{% block content %}
    {{ super() }}
    <body>
        <div class="profile-container">
            <header>
                <div>
                    <h2>Личный кабинет</h2>
                </div>
                <div class="user-info">
                    {% block user_data %}
                    {%if user_data%}
        
                    <h2> {{ user_data['first_name'] }} {{ user_data['last_name'] }} {{ user_data['patronymic'] }}</h2>
                    {% endif %}
                    {%endblock%}
                    <a href="{{ url_for('auth.logout') }}">Выйти</a>
                </div> 
            </header>
            <main>
                    <section class="orders">
                        <h2>Заказы</h2>
                        <table id="orders-table">
                            <thead>
                                <tr>
                                    <th>Проблема</th>
                                    <th>Дата</th>
                                    <th>Девайс</th>
                                    <th>Статус</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>{{ order.name }}</td>
                                    <td>{{ order.date }}</td>
                                    <td>{{ order.device }}</td>
                                    <td>{{ order.status }}</td>
                                </tr>
                                {% else %}
                                <tr>
                                    <td colspan="4" style="text-align: center;">Нет заказов</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </section>
                <button id="new-order-btn" >
                    <a href="{{ url_for('order.make_order') }}">Оформить новый заказ</a>
                </button>
            </main>
            <script src="script.js"></script>
        </div>
    </body>
{% endblock %}

serviceproj/templates/unauthorized.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <div class="modern-content-page">
        <div class="modern-content">
           <h2> Зарегестрируйтесь или войдите в аккаунт</h2>
           <tr>
            <td><a href="{{ url_for('auth.register') }}" class="btn"> Register</a></td>
            <td><a href="{{ url_for('auth.login') }}" class="btn"> Login</a></td>
           </tr>
        </div>
    </div>
</body>
</html>